Amigo_web_server:
  ip_address: "192.168.10.54"
  port: 80
  port_mongo: 27017
  port_ssh: 2212
  usr_ssh: "amigo"
  pass_ssh: "am1g0oN370v3"
  Mongo_DB: "AMIGO_DB_SIBUR"

ESS_s:
  ESS_1:
    mrid: "_ESS_01"
    p_nom: 18
    e_nom: 20

PVS_s:
  PVS_1:
    mrid: "_PVS_01"

Grid_s:
  Grid_1:
    mrid: "_EXG_01"
    p_grid_delta: 5