Amigo_web_server:
  ip_address: "192.168.10.254"
  port: 80
  port_mongo: 27017
  port_ssh: 22
  usr_ssh: "admin"
  pass_ssh: "admin"
  Mongo_DB: "TEMPLATE_DB"

ESS_s:
  ESS_1:
    mrid: "_ESS_01"
    p_nom: 328
    e_nom: 328

PVS_s:
  PVS_1:
    mrid: "_PVS_01"

Grid_s:
  Grid_1:
    mrid: "_EXG_01"
    p_grid_delta: 5